#!/bin/dash
if [ "$#" -ne 2 ]; then
	echo "Usage: ./pushy-commit -m message"
	exit 1
fi

cd ".pushy/.index"|| exit 1;
pattern='^[^-]*$'
[ ! "$1" = "-m" ] && echo "Error: Needs -m specifier" && exit 1

if echo "$2" | grep -Eq "$pattern";
then
	cp -R ./ ../	
fi
cd ../ || exit 1
count=$(< log.txt wc -l)
echo "Commited as commit $count"
echo "$count $2" >> log.txt
