#!/bin/dash
# if [ "$#" -lt 2 ]; then
# 	echo "Usage: ./pushy-commit [-a] -m message"
# 	exit 1
# fi

usage () { echo "Usage: ./pushy-commit [-a] -m message"; exit 1; }

if [ "$#" -lt 2 ]; then
	usage
fi

a=0
m=""
while getopts "am:" o;
do
	case "${o}" in
		a)
			a=1
			;;
		m)
			m=${OPTARG}
			;;
		*)
			usage
			;;
	esac
done

echo "${a}"
echo "${m}"

[ ! "$m" ] && usage

cd ".pushy" || exit
[ ! -d ".commits" ] && mkdir -p ".commits"
count=$(< log.txt wc -l)
mkdir -p ".commits/$count"
cd ".index"|| exit 1;
pattern='^[^-]*$'
if echo "$m" | grep -Eq "$pattern";
then
	changes=0

	if [ "$a" ]:
	then
		for file in *
		do
			#Get contents from current directory added to index
			cp "../../$file" "$file"
		done
	fi

	for file in *
	do
		#First check the if file exists in repo
		if [ ! -f "../$file" ];
		then
			changes=$((changes + 1))
		#Next check if the same as existing file
		elif ! cmp -s "$file" "../$file";
		then
			changes=$((changes + 1))
		fi
	done
	if [ "$changes" -eq 0 ];
	then
		echo "nothing to commit"
		exit 1
	else
	for file in *
	do
		cp "$file" "../$file"
		cp "$file" "../.commits/$count/$file"
	done
	fi
fi
cd ../ || exit 1

echo "Committed as commit $count"
echo "$count $2" >> log.txt
