#!/bin/dash

if [ "$#" -ne 1 ]; then
	echo "Usage: ./pushy-show [commit]:filename"
fi
pattern='^[0-9]*:[a-zA-Z0-9[a-zA-Z0-9.-_]*$'

if echo "$1" | grep -Eq "$pattern";
then
	file="${1#*:}"
	commit="${1%:*}"
	dir=".pushy/.commits/$commit"

	if [ ! "$commit" ];
	then
		dir=".pushy/.index"

		if [ ! -f "$dir/$file" ];
		then
			echo "pushy-show: error: '""$file""' not found in index"
			exit 1
		fi
	fi

	if [ ! -d "$dir" ];
	then
		echo "pushy-show: error: unknown commit '""$commit""'"
		exit 1
	fi

	if [ ! -f "$dir/$file" ];
	then
		echo "pushy-show: error: '""$file""' not found in commit $commit"
		exit 1
	fi


	cd "$dir" || exit 1
	cat "$file"
fi
