#!/bin/dash
pattern='^[a-zA-Z0-9[a-zA-Z0-9.-_]*$'
if [ ! -d ".pushy" ];
then
	echo "pushy-add: error: pushy repository directory .pushy not found"
	exit 1
fi
for file in "$@"
do
	if [ ! -f "$file" ];
	then
		echo "pushy-add: error: can not open '$file'"
		exit 1
	fi
	if echo "$file" | grep -Eq  "$pattern";
	then
		mkdir -p ".pushy/.index"
		cp -R "$file" ".pushy/.index"
	fi
done
