#!/bin/dash
[ -d ".pushy" ] && { echo "pushy-init: error: .pushy already exists"; exit 1; }
mkdir -p ".pushy" && echo "Initialized empty pushy repository in .pushy"
cd ".pushy" || exit 1
touch "log.txt"
