#!/bin/dash
if [ "$#" -ne 2 ]; then
	echo "Usage: ./pushy-commit -m message"
	exit 1
fi
[ ! "$1" = "-m" ] && echo "Error: Needs -m specifier" && exit 1

cd ".pushy" || exit
[ ! -d ".commits" ] && mkdir -p ".commits"
count=$(< log.txt wc -l)
mkdir -p ".commits/$count"
cd ".index"|| exit 1;
pattern='^[^-]*$'
if echo "$2" | grep -Eq "$pattern";
then
	# dirdiff=$(diff ./ ../)
	# echo "$dirdiff"
	# if [ "$dirdiff"=0 ]; then
	# 	for file in ./*
	# 	do
	# 		cp "$file" "../$file"
	# 		cp "$file" "../.commits/$count/$file"
	# 	done
	# fi
	# if [ "$dirdiff"=1 ]; then
	# 	echo "nothing to commit"
	# fi

	changes=0
	for file in *
	do
		#First check the if file exists
		if [ ! -f "../$file" ];
		then
			changes=$((changes + 1))
		#Next check if the same as existing file
		elif ! cmp -s "$file" "../$file";
		then
			changes=$((changes + 1))
		fi
	done
	if [ "$changes" -eq 0 ];
	then
		echo "nothing to commit"
		exit 1
	else
	for file in *
	do
		cp "$file" "../$file"
		cp "$file" "../.commits/$count/$file"
	done
	fi
fi
cd ../ || exit 1

echo "Committed as commit $count"
echo "$count $2" >> log.txt
