#!/bin/dash
pattern='^[a-zA-Z0-9[a-zA-Z0-9.-_]*$'
if [ ! -d ".pushy" ];
then
	echo "pushy-add: error: pushy repository directory .pushy not found"
	exit 1
fi
for file in "$@"
do
	#If exists in index, but not in working, stage for deletion
	if [ -f ".pushy/.index/$file" -a ! -f "$file" ];
	then
		rm ".pushy/.index/$file"
	#If doesn't exist in index and doesn't exist in working, error
	elif [ ! -f "$file" ];
	then
		echo "pushy-add: error: can not open '$file'"
		exit 1
	elif echo "$file" | grep -Eq  "$pattern";
	then
		mkdir -p ".pushy/.index"
		cp -R "$file" ".pushy/.index"
	fi
done
